services:
  db:
    image: postgres:14
    container_name: student-db
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api1:
    build: .
    image: student-api:1.2.1
    container_name: student-api-1
    environment:
      PORT: 5000
      DEBUG: "false"
      DATABASE_URL: postgresql://student_user:student_pass@db:5432/students
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api2:
    build: .
    image: student-api:1.2.1
    container_name: student-api-2
    environment:
      PORT: 5000
      DEBUG: "false"
      DATABASE_URL: postgresql://student_user:student_pass@db:5432/students
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: student-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
