services:
  db:
    image: postgres:14
    container_name: student-db
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: student-api:1.2.1
    container_name: student-api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DEBUG: "false"
      DATABASE_URL: postgresql://student_user:student_pass@db:5432/students
    depends_on:
      - db
volumes:
  postgres_data:
